### ISSUE TITLE
Verwendung von Github Pages

### ISSUE THREAD

**Issue by FabianGeiselhart** [iot-wetterstation/iot_wetterdaten#1]
Wir hatten ja die Idee, dass wir das alles über einen vServer verfügbar machen.

Allerdings könnte man das wesentlich einfacher machen (glaube ich), indem wir alles über die Github Pages funktion anzeigen. Das Problem ist halt, dass Github Pages kein PHP unterstützt. Hätte da jemand eine Idee, bzw. weiß jemand, ob das funktionieren würde?

**Comment by ThomasKoscheck** [comment]
Wie sieht es aus mit anderen Sprachen?
Aspx oder so?

**Comment by FabianGeiselhart** [comment]
So wie ich das sehe, gibt es bei den Github Pages keine Serverseitigen Sprachen, was bedeutet, dass alles mit JS machen müssten...
